//! Prepopulated store data for tests.
//! Generated by the `build-snapshot` bin.
//! Regenerate: cargo run -p tb_domain --bin build-snapshot --features test-support

/// Formatted JSON snapshot of the prepopulated store.
/// This is a pretty-printed JSON string that gets deserialized by MemStore::prepopulated().
pub const SNAPSHOT_JSON: &str = r#"{
  "users": [
    {
      "id": 1,
      "name": "Bike",
      "firstname": "Tenda",
      "avatar": null,
      "is_admin": false,
      "onboarding_status": "pending"
    }
  ],
  "parts": [
    {
      "id": 1,
      "owner": 1,
      "what": 1,
      "name": "Main Bike",
      "vendor": "TendaBike",
      "model": "Standard Frame",
      "purchase": "2022-11-14T22:00:00Z",
      "last_used": "2023-05-19T22:00:00Z",
      "disposed_at": null,
      "usage": "01a0bb12-3570-7d83-b2b2-9308156a4379",
      "source": null,
      "shop": null
    },
    {
      "id": 2,
      "owner": 1,
      "what": 2,
      "name": "Front Wheel A",
      "vendor": "Zipp",
      "model": "404 Firecrest",
      "purchase": "2023-01-01T00:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a0bb12-3570-7d83-b2b2-931309886fa1",
      "source": null,
      "shop": null
    },
    {
      "id": 3,
      "owner": 1,
      "what": 5,
      "name": "Rear Wheel A",
      "vendor": "DT Swiss",
      "model": "XR 1501",
      "purchase": "2023-01-01T00:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a0bb12-3570-7d83-b2b2-932b2c49c00a",
      "source": null,
      "shop": null
    },
    {
      "id": 4,
      "owner": 1,
      "what": 4,
      "name": "Chain A",
      "vendor": "Shimano",
      "model": "CN-M510",
      "purchase": "2023-01-01T00:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a0bb12-3570-7d83-b2b2-93361f58866d",
      "source": null,
      "shop": null
    },
    {
      "id": 5,
      "owner": 1,
      "what": 3,
      "name": "Tire Front A",
      "vendor": "Continental",
      "model": "GP5000",
      "purchase": "2023-01-01T00:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a0bb12-3570-7d83-b2b2-934ae2196cca",
      "source": null,
      "shop": null
    },
    {
      "id": 6,
      "owner": 1,
      "what": 3,
      "name": "Tire Rear A",
      "vendor": "Continental",
      "model": "GP5000 ST",
      "purchase": "2023-01-01T00:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a0bb12-3570-7d83-b2b2-935365a98c46",
      "source": null,
      "shop": null
    },
    {
      "id": 7,
      "owner": 1,
      "what": 1,
      "name": "Road Bike",
      "vendor": "Trek",
      "model": "Domane",
      "purchase": "2022-11-14T22:00:00Z",
      "last_used": "2022-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a0bb12-3571-7d42-8499-fee0fa984276",
      "source": null,
      "shop": null
    },
    {
      "id": 8,
      "owner": 1,
      "what": 2,
      "name": "Front Wheel B",
      "vendor": "Mavic",
      "model": "Carbon WS",
      "purchase": "2023-01-01T00:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a0bb12-3571-7d42-8499-fef7a8a35436",
      "source": null,
      "shop": null
    },
    {
      "id": 9,
      "owner": 1,
      "what": 5,
      "name": "Rear Wheel B",
      "vendor": "Mavic",
      "model": "Carbon WS",
      "purchase": "2023-01-01T00:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a0bb12-3571-7d42-8499-ff0550db33b7",
      "source": null,
      "shop": null
    },
    {
      "id": 10,
      "owner": 1,
      "what": 4,
      "name": "Chain B",
      "vendor": "SRAM",
      "model": "PC-XX1",
      "purchase": "2023-01-01T00:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a0bb12-3571-7d42-8499-ff1eb617d2d1",
      "source": null,
      "shop": null
    },
    {
      "id": 11,
      "owner": 1,
      "what": 3,
      "name": "Tire Front B",
      "vendor": "Schwalbe",
      "model": "One",
      "purchase": "2023-01-01T00:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a0bb12-3571-7d42-8499-ff2d8828accf",
      "source": null,
      "shop": null
    },
    {
      "id": 12,
      "owner": 1,
      "what": 3,
      "name": "Tire Rear B",
      "vendor": "Schwalbe",
      "model": "One Plus",
      "purchase": "2023-01-01T00:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a0bb12-3571-7d42-8499-ff39cf4923c8",
      "source": null,
      "shop": null
    },
    {
      "id": 13,
      "owner": 1,
      "what": 4,
      "name": "Spare Chain 1",
      "vendor": "Shimano",
      "model": "HG-54",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a0bb12-3571-7d42-8499-ffe8ff782328",
      "source": null,
      "shop": null
    },
    {
      "id": 14,
      "owner": 1,
      "what": 4,
      "name": "Spare Chain 2",
      "vendor": "SRAM",
      "model": "PC-1031",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a0bb12-3571-7d42-8499-fff6116d6ab3",
      "source": null,
      "shop": null
    },
    {
      "id": 15,
      "owner": 1,
      "what": 3,
      "name": "Spare Tire",
      "vendor": "Continental",
      "model": "Supersonic",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a0bb12-3571-7d42-849a-000b1c5f6a63",
      "source": null,
      "shop": null
    },
    {
      "id": 16,
      "owner": 1,
      "what": 2,
      "name": "Spare Wheel",
      "vendor": "HED",
      "model": "Stinger 3",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a0bb12-3571-7d42-849a-001513a91707",
      "source": null,
      "shop": null
    },
    {
      "id": 17,
      "owner": 1,
      "what": 3,
      "name": "Spare Wheel Tire",
      "vendor": "Continental",
      "model": "GP5000",
      "purchase": "2023-01-01T00:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a0bb12-3571-7d42-849a-002c7fe2ef8e",
      "source": null,
      "shop": null
    }
  ],
  "attachments": [
    {
      "part_id": 2,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 1,
      "hook": 1,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a0bb12-3570-7d83-b2b2-9372c8c30395"
    },
    {
      "part_id": 3,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 1,
      "hook": 1,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a0bb12-3570-7d83-b2b2-939fd1656828"
    },
    {
      "part_id": 4,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 1,
      "hook": 1,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a0bb12-3570-7d83-b2b2-93b48e8c159d"
    },
    {
      "part_id": 5,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 1,
      "hook": 2,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a0bb12-3571-7d42-8499-feb96957a6ea"
    },
    {
      "part_id": 6,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 1,
      "hook": 5,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a0bb12-3571-7d42-8499-fed693a2d32e"
    },
    {
      "part_id": 8,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 7,
      "hook": 1,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a0bb12-3571-7d42-8499-ff50396f698b"
    },
    {
      "part_id": 9,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 7,
      "hook": 1,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a0bb12-3571-7d42-8499-ff7173f39984"
    },
    {
      "part_id": 10,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 7,
      "hook": 1,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a0bb12-3571-7d42-8499-ff9dadf1f7db"
    },
    {
      "part_id": 11,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 7,
      "hook": 2,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a0bb12-3571-7d42-8499-ffb0567d38c6"
    },
    {
      "part_id": 12,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 7,
      "hook": 5,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a0bb12-3571-7d42-8499-ffdc9695830e"
    },
    {
      "part_id": 17,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 16,
      "hook": 2,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a0bb12-3571-7d42-849a-004ab16c5751"
    }
  ],
  "usages": [
    {
      "id": "01a0bb12-3570-7d83-b2b2-9308156a4379",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a0bb12-3570-7d83-b2b2-931309886fa1",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a0bb12-3570-7d83-b2b2-932b2c49c00a",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a0bb12-3570-7d83-b2b2-93361f58866d",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a0bb12-3570-7d83-b2b2-934ae2196cca",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a0bb12-3570-7d83-b2b2-935365a98c46",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a0bb12-3570-7d83-b2b2-9372c8c30395",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a0bb12-3570-7d83-b2b2-939fd1656828",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a0bb12-3570-7d83-b2b2-93b48e8c159d",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a0bb12-3571-7d42-8499-feb96957a6ea",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a0bb12-3571-7d42-8499-fed693a2d32e",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    }
  ],
  "activities": [
    {
      "id": 1,
      "user_id": 1,
      "what": 1,
      "name": "Morning Ride",
      "start": "2023-05-18T22:13:20Z",
      "duration": 3600,
      "time": 25,
      "distance": 50000,
      "climb": 400,
      "descend": null,
      "energy": 500,
      "gear": 1,
      "device_name": null,
      "external_id": null
    },
    {
      "id": 2,
      "user_id": 1,
      "what": 1,
      "name": "Hill Repeats",
      "start": "2023-05-19T00:13:20Z",
      "duration": 1800,
      "time": 5200,
      "distance": 40000,
      "climb": 600,
      "descend": null,
      "energy": 500,
      "gear": 1,
      "device_name": null,
      "external_id": null
    },
    {
      "id": 3,
      "user_id": 1,
      "what": 1,
      "name": "Recovery Spin",
      "start": "2023-05-19T22:13:20Z",
      "duration": 2400,
      "time": 2800,
      "distance": 35000,
      "climb": 100,
      "descend": null,
      "energy": 500,
      "gear": 1,
      "device_name": null,
      "external_id": null
    }
  ]
}"#;
