//! Prepopulated store data for tests.
//! Generated by the `build-snapshot` bin.
//! Regenerate: cargo run -p tb_domain --bin build-snapshot --features test-support

/// Formatted JSON snapshot of the prepopulated store.
/// This is a pretty-printed JSON string that gets deserialized by MemStore::prepopulated().
pub const SNAPSHOT_JSON: &str = r#"{
  "parts": [
    {
      "id": 1,
      "owner": 1,
      "what": 1,
      "name": "Main Bike",
      "vendor": "TendaBike",
      "model": "Standard Frame",
      "purchase": "2022-11-14T22:00:00Z",
      "last_used": "2023-05-19T22:00:00Z",
      "disposed_at": null,
      "usage": "01a056ae-368e-7f30-8fd0-606bab738668",
      "source": null,
      "notes": "Main bike frame",
      "shop": null
    },
    {
      "id": 2,
      "owner": 1,
      "what": 2,
      "name": "Front Wheel A",
      "vendor": "Zipp",
      "model": "404 Firecrest",
      "purchase": "2023-05-18T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a056ae-368e-7f30-8fd0-607c102725ed",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 3,
      "owner": 1,
      "what": 5,
      "name": "Rear Wheel A",
      "vendor": "DT Swiss",
      "model": "XR 1501",
      "purchase": "2023-05-18T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a056ae-368e-7f30-8fd0-608b4e9c7e23",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 4,
      "owner": 1,
      "what": 4,
      "name": "Chain A",
      "vendor": "Shimano",
      "model": "CN-M510",
      "purchase": "2023-05-18T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a056ae-368e-7f30-8fd0-6095bde6bf3a",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 5,
      "owner": 1,
      "what": 3,
      "name": "Tire Front A",
      "vendor": "Continental",
      "model": "GP5000",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a056ae-368e-7f30-8fd0-60a3c9090b7d",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 6,
      "owner": 1,
      "what": 3,
      "name": "Tire Rear A",
      "vendor": "Continental",
      "model": "GP5000 ST",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a056ae-368e-7f30-8fd0-60b235dc748d",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 7,
      "owner": 1,
      "what": 1,
      "name": "Road Bike",
      "vendor": "Trek",
      "model": "Domane",
      "purchase": "2022-11-14T22:00:00Z",
      "last_used": "2022-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a056ae-368e-7f30-8fd0-6123e70ff07f",
      "source": null,
      "notes": "Road bike frame",
      "shop": null
    },
    {
      "id": 8,
      "owner": 1,
      "what": 2,
      "name": "Front Wheel B",
      "vendor": "Mavic",
      "model": "Carbon WS",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a056ae-368e-7f30-8fd0-613a651478e1",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 9,
      "owner": 1,
      "what": 5,
      "name": "Rear Wheel B",
      "vendor": "Mavic",
      "model": "Carbon WS",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a056ae-368e-7f30-8fd0-614b47b2a947",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 10,
      "owner": 1,
      "what": 4,
      "name": "Chain B",
      "vendor": "SRAM",
      "model": "PC-XX1",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a056ae-368e-7f30-8fd0-615f684ea140",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 11,
      "owner": 1,
      "what": 3,
      "name": "Tire Front B",
      "vendor": "Schwalbe",
      "model": "One",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a056ae-368e-7f30-8fd0-61661310f7b5",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 12,
      "owner": 1,
      "what": 3,
      "name": "Tire Rear B",
      "vendor": "Schwalbe",
      "model": "One Plus",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a056ae-368e-7f30-8fd0-6176931f5c4a",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 13,
      "owner": 1,
      "what": 4,
      "name": "Spare Chain 1",
      "vendor": "Shimano",
      "model": "HG-54",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a056ae-368e-7f30-8fd0-61ea7ca7f1e1",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 14,
      "owner": 1,
      "what": 4,
      "name": "Spare Chain 2",
      "vendor": "SRAM",
      "model": "PC-1031",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a056ae-368e-7f30-8fd0-61f676551da1",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 15,
      "owner": 1,
      "what": 3,
      "name": "Spare Tire",
      "vendor": "Continental",
      "model": "Supersonic",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a056ae-368e-7f30-8fd0-620a29ea9334",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 16,
      "owner": 1,
      "what": 2,
      "name": "Spare Wheel",
      "vendor": "HED",
      "model": "Stinger 3",
      "purchase": "2023-05-18T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a056ae-368e-7f30-8fd0-621da2b08a96",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 17,
      "owner": 1,
      "what": 3,
      "name": "Spare Wheel Tire",
      "vendor": "Continental",
      "model": "GP5000",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a056ae-368e-7f30-8fd0-622a6f6276a1",
      "source": null,
      "notes": "Test part",
      "shop": null
    }
  ],
  "attachments": [
    {
      "part_id": 2,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 1,
      "hook": 1,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a056ae-368e-7f30-8fd0-60cb76ad32f7"
    },
    {
      "part_id": 3,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 1,
      "hook": 1,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a056ae-368e-7f30-8fd0-60d90e7a7729"
    },
    {
      "part_id": 4,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 1,
      "hook": 1,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a056ae-368e-7f30-8fd0-60e62611e7cc"
    },
    {
      "part_id": 5,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 2,
      "hook": 3,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a056ae-368e-7f30-8fd0-60fdcf1b2aeb"
    },
    {
      "part_id": 6,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 2,
      "hook": 3,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a056ae-368e-7f30-8fd0-610ce31f0598"
    },
    {
      "part_id": 6,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 3,
      "hook": 3,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a056ae-368e-7f30-8fd0-611a336cbeae"
    },
    {
      "part_id": 8,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 7,
      "hook": 1,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a056ae-368e-7f30-8fd0-618c1349bd38"
    },
    {
      "part_id": 9,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 7,
      "hook": 1,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a056ae-368e-7f30-8fd0-6198ae241db9"
    },
    {
      "part_id": 10,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 7,
      "hook": 1,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a056ae-368e-7f30-8fd0-61a9a24fa2bd"
    },
    {
      "part_id": 11,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 8,
      "hook": 3,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a056ae-368e-7f30-8fd0-61bdbbb014dc"
    },
    {
      "part_id": 12,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 8,
      "hook": 3,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a056ae-368e-7f30-8fd0-61c2a7b2bf0e"
    },
    {
      "part_id": 12,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 9,
      "hook": 3,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a056ae-368e-7f30-8fd0-61d3b1534cbe"
    },
    {
      "part_id": 16,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 1,
      "hook": 1,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a056ae-368e-7f30-8fd0-623238160d16"
    },
    {
      "part_id": 17,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 16,
      "hook": 3,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a056ae-368e-7f30-8fd0-62455fd84436"
    }
  ],
  "usages": [
    {
      "id": "01a056ae-368e-7f30-8fd0-606bab738668",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a056ae-368e-7f30-8fd0-607c102725ed",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a056ae-368e-7f30-8fd0-608b4e9c7e23",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a056ae-368e-7f30-8fd0-6095bde6bf3a",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a056ae-368e-7f30-8fd0-60cb76ad32f7",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a056ae-368e-7f30-8fd0-60d90e7a7729",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a056ae-368e-7f30-8fd0-60e62611e7cc",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a056ae-368e-7f30-8fd0-621da2b08a96",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a056ae-368e-7f30-8fd0-623238160d16",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    }
  ],
  "activities": [
    {
      "id": 1,
      "user_id": 1,
      "what": 1,
      "name": "Morning Ride",
      "start": "2023-05-18T22:13:20Z",
      "duration": 3600,
      "time": 25,
      "distance": 50000,
      "climb": 400,
      "descend": null,
      "energy": 500,
      "gear": 1,
      "device_name": null,
      "external_id": null
    },
    {
      "id": 1,
      "user_id": 1,
      "what": 1,
      "name": "Hill Repeats",
      "start": "2023-05-19T00:13:20Z",
      "duration": 1800,
      "time": 5200,
      "distance": 40000,
      "climb": 600,
      "descend": null,
      "energy": 500,
      "gear": 1,
      "device_name": null,
      "external_id": null
    },
    {
      "id": 1,
      "user_id": 1,
      "what": 1,
      "name": "Recovery Spin",
      "start": "2023-05-19T22:13:20Z",
      "duration": 2400,
      "time": 2800,
      "distance": 35000,
      "climb": 100,
      "descend": null,
      "energy": 500,
      "gear": 1,
      "device_name": null,
      "external_id": null
    }
  ]
}"#;
