//! Prepopulated store data for tests.
//! Generated by the `build-snapshot` bin.
//! Regenerate: cargo run -p tb_domain --bin build-snapshot --features test-support

/// Formatted JSON snapshot of the prepopulated store.
/// This is a pretty-printed JSON string that gets deserialized by MemStore::prepopulated().
pub const SNAPSHOT_JSON: &str = r#"{
  "users": [
    {
      "id": 1,
      "name": "Bike",
      "firstname": "Tenda",
      "avatar": null,
      "is_admin": false,
      "onboarding_status": "pending"
    }
  ],
  "parts": [
    {
      "id": 1,
      "owner": 1,
      "what": 1,
      "name": "Main Bike",
      "vendor": "TendaBike",
      "model": "Standard Frame",
      "purchase": "2022-11-14T22:00:00Z",
      "last_used": "2023-05-19T22:00:00Z",
      "disposed_at": null,
      "usage": "01a06db9-9eff-7010-8fa4-b72c1ca8aab1",
      "source": null,
      "notes": "Main bike frame",
      "shop": null
    },
    {
      "id": 2,
      "owner": 1,
      "what": 2,
      "name": "Front Wheel A",
      "vendor": "Zipp",
      "model": "404 Firecrest",
      "purchase": "2023-05-18T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a06db9-9eff-7010-8fa4-b73c5260782a",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 3,
      "owner": 1,
      "what": 5,
      "name": "Rear Wheel A",
      "vendor": "DT Swiss",
      "model": "XR 1501",
      "purchase": "2023-05-18T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a06db9-9eff-7010-8fa4-b74734d538df",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 4,
      "owner": 1,
      "what": 4,
      "name": "Chain A",
      "vendor": "Shimano",
      "model": "CN-M510",
      "purchase": "2023-05-18T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a06db9-9eff-7010-8fa4-b7507ca842c6",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 5,
      "owner": 1,
      "what": 3,
      "name": "Tire Front A",
      "vendor": "Continental",
      "model": "GP5000",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a06db9-9eff-7010-8fa4-b76127f2a50e",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 6,
      "owner": 1,
      "what": 3,
      "name": "Tire Rear A",
      "vendor": "Continental",
      "model": "GP5000 ST",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a06db9-9eff-7010-8fa4-b7764cf0cd19",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 7,
      "owner": 1,
      "what": 1,
      "name": "Road Bike",
      "vendor": "Trek",
      "model": "Domane",
      "purchase": "2022-11-14T22:00:00Z",
      "last_used": "2022-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a06db9-9eff-7010-8fa4-b7d89bacfc15",
      "source": null,
      "notes": "Road bike frame",
      "shop": null
    },
    {
      "id": 8,
      "owner": 1,
      "what": 2,
      "name": "Front Wheel B",
      "vendor": "Mavic",
      "model": "Carbon WS",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a06db9-9eff-7010-8fa4-b7e6ba3ae9d0",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 9,
      "owner": 1,
      "what": 5,
      "name": "Rear Wheel B",
      "vendor": "Mavic",
      "model": "Carbon WS",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a06db9-9eff-7010-8fa4-b7fdc65c643d",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 10,
      "owner": 1,
      "what": 4,
      "name": "Chain B",
      "vendor": "SRAM",
      "model": "PC-XX1",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a06db9-9eff-7010-8fa4-b80bc800ee9d",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 11,
      "owner": 1,
      "what": 3,
      "name": "Tire Front B",
      "vendor": "Schwalbe",
      "model": "One",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a06db9-9eff-7010-8fa4-b8165ae597a9",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 12,
      "owner": 1,
      "what": 3,
      "name": "Tire Rear B",
      "vendor": "Schwalbe",
      "model": "One Plus",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a06db9-9eff-7010-8fa4-b8283b792898",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 13,
      "owner": 1,
      "what": 4,
      "name": "Spare Chain 1",
      "vendor": "Shimano",
      "model": "HG-54",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a06db9-9eff-7010-8fa4-b88fdcc9df84",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 14,
      "owner": 1,
      "what": 4,
      "name": "Spare Chain 2",
      "vendor": "SRAM",
      "model": "PC-1031",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a06db9-9eff-7010-8fa4-b899eac629d3",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 15,
      "owner": 1,
      "what": 3,
      "name": "Spare Tire",
      "vendor": "Continental",
      "model": "Supersonic",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a06db9-9eff-7010-8fa4-b8ab4c3b754e",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 16,
      "owner": 1,
      "what": 2,
      "name": "Spare Wheel",
      "vendor": "HED",
      "model": "Stinger 3",
      "purchase": "2023-05-18T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a06db9-9eff-7010-8fa4-b8b261929c00",
      "source": null,
      "notes": "Test part",
      "shop": null
    },
    {
      "id": 17,
      "owner": 1,
      "what": 3,
      "name": "Spare Wheel Tire",
      "vendor": "Continental",
      "model": "GP5000",
      "purchase": "2023-11-14T22:00:00Z",
      "last_used": "2023-11-14T22:00:00Z",
      "disposed_at": null,
      "usage": "01a06db9-9eff-7010-8fa4-b8cc567d7a15",
      "source": null,
      "notes": "Test part",
      "shop": null
    }
  ],
  "attachments": [
    {
      "part_id": 2,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 1,
      "hook": 1,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a06db9-9eff-7010-8fa4-b78aa9b8ccdc"
    },
    {
      "part_id": 3,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 1,
      "hook": 1,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a06db9-9eff-7010-8fa4-b7934c5ff27a"
    },
    {
      "part_id": 4,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 1,
      "hook": 1,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a06db9-9eff-7010-8fa4-b7ac3c6ce035"
    },
    {
      "part_id": 5,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 2,
      "hook": 3,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a06db9-9eff-7010-8fa4-b7b290957911"
    },
    {
      "part_id": 6,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 3,
      "hook": 3,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a06db9-9eff-7010-8fa4-b7cf4d5c3fb1"
    },
    {
      "part_id": 8,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 7,
      "hook": 1,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a06db9-9eff-7010-8fa4-b83e12d08e22"
    },
    {
      "part_id": 9,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 7,
      "hook": 1,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a06db9-9eff-7010-8fa4-b8478fc9a9b6"
    },
    {
      "part_id": 10,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 7,
      "hook": 1,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a06db9-9eff-7010-8fa4-b8579dd40219"
    },
    {
      "part_id": 11,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 8,
      "hook": 3,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a06db9-9eff-7010-8fa4-b86a9736ec4f"
    },
    {
      "part_id": 12,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 9,
      "hook": 3,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a06db9-9eff-7010-8fa4-b87348bbc861"
    },
    {
      "part_id": 16,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 1,
      "hook": 1,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a06db9-9eff-7010-8fa4-b8d031a29efe"
    },
    {
      "part_id": 17,
      "attached": "2023-01-01T00:00:00Z",
      "gear": 16,
      "hook": 3,
      "detached": "9100-01-01T00:00:00Z",
      "usage": "01a06db9-9eff-7010-8fa4-b8e4669dd125"
    }
  ],
  "usages": [
    {
      "id": "01a06db9-9eff-7010-8fa4-b72c1ca8aab1",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a06db9-9eff-7010-8fa4-b73c5260782a",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a06db9-9eff-7010-8fa4-b74734d538df",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a06db9-9eff-7010-8fa4-b7507ca842c6",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a06db9-9eff-7010-8fa4-b78aa9b8ccdc",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a06db9-9eff-7010-8fa4-b7934c5ff27a",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a06db9-9eff-7010-8fa4-b7ac3c6ce035",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a06db9-9eff-7010-8fa4-b8b261929c00",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    },
    {
      "id": "01a06db9-9eff-7010-8fa4-b8d031a29efe",
      "time": 8025,
      "distance": 125000,
      "climb": 1100,
      "descend": 1100,
      "energy": 1500,
      "count": 3
    }
  ],
  "activities": [
    {
      "id": 1,
      "user_id": 1,
      "what": 1,
      "name": "Morning Ride",
      "start": "2023-05-18T22:13:20Z",
      "duration": 3600,
      "time": 25,
      "distance": 50000,
      "climb": 400,
      "descend": null,
      "energy": 500,
      "gear": 1,
      "device_name": null,
      "external_id": null
    },
    {
      "id": 1,
      "user_id": 1,
      "what": 1,
      "name": "Hill Repeats",
      "start": "2023-05-19T00:13:20Z",
      "duration": 1800,
      "time": 5200,
      "distance": 40000,
      "climb": 600,
      "descend": null,
      "energy": 500,
      "gear": 1,
      "device_name": null,
      "external_id": null
    },
    {
      "id": 1,
      "user_id": 1,
      "what": 1,
      "name": "Recovery Spin",
      "start": "2023-05-19T22:13:20Z",
      "duration": 2400,
      "time": 2800,
      "distance": 35000,
      "climb": 100,
      "descend": null,
      "energy": 500,
      "gear": 1,
      "device_name": null,
      "external_id": null
    }
  ]
}"#;
