#!/bin/sh
protected_branch='main'

while read local_ref local_sha remote_ref remote_sha
do
    case "$remote_ref" in
        *"$protected_branch")
            if [ "$local_sha" = "0000000000000000000000000000000000000000" ]; then
                echo "Deleting '$protected_branch' is not allowed."
                exit 1
            fi
            ;;
    esac
done
exit 0
