FROM node:21 AS build-frontend

WORKDIR /frontend

COPY frontend/package.json frontend/package-lock.json /frontend/
RUN npm update rollup

COPY frontend/ /frontend
RUN npm run build

FROM gcr.io/distroless/cc

USER 999:999
WORKDIR /tendabike

COPY --chmod=755 tendabike .
COPY libpq.so.5 /lib/x86_64-linux-gnu/libpq.so.5
COPY --from=build-frontend /frontend/dist dist

ENV STATIC_WWW="/tendabike/dist"

ENTRYPOINT [ "./tendabike" ]
