FROM gcr.io/distroless/cc-debian12:latest

USER 999:999
WORKDIR /tendabike

COPY --chmod=755 tendabike .
COPY dist dist
COPY libs/* /usr/local/lib/

ENV STATIC_WWW="/tendabike/dist"

ENTRYPOINT [ "./tendabike" ]
