[global]
address = "0.0.0.0"
port = 8000
template_dir="templates"
secret_key="8two500UmM6efszt3zcVt6WDhmWOZwvVItuM9LF33iE="

[global.databases]
app_db={url="postgres://localhost/tendabike3"}
auth_db={url="postgres://localhost/strava"}

