@host = http://[::1]:8000

{{host}}/part/types 
x-user-id: 2
###
{{host}}/ 
x-user-id: 2
###
{{host}}/part/mygear 
x-user-id: 2
###
{{host}}/part/myspares 
x-user-id: 2
###
{{host}}/part/1 
x-user-id: 2
###
{{host}}/part/1?assembly 
x-user-id: 2
###
Get {{host}}/activ/9 
x-user-id: 2
###
PATCH {{host}}/activ/9?gear= 
x-user-id: 2
###
PATCH  {{host}}/activ/update/6 
x-user-id: 2
###
DELETE   {{host}}/activ/302 
x-user-id: 2
