@host = http://[::1]:8000
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzM3MzU2MzIsImV4cCI6MTU3Mzc1NjkzMiwiaWQiOjJ9.vLxuJS4EFCI5E_M7gm6nNNrv8gKvPcKXHyWMemHlcAM
{{host}}/types/part/2
Authorization: Bearer {{token}}
###
{{host}}/user
Authorization: Bearer {{token}}
###
{{host}}/part/mygear 
Authorization: Bearer {{token}}
###
{{host}}/part/myspares 
Authorization: Bearer {{token}}
###
{{host}}/attach/assembly/1
Authorization: Bearer {{token}}
###
POST {{host}}/part
Authorization: Bearer {{token}}

{
    "owner": 2,
    "what": 1,
    "name": "test",
    "vendor": "test vendor",
    "model": "test model"
}
###
{{host}}/part/302?assembly&time=2018-11-21T02:00:00
Authorization: Bearer {{token}}
###
Get {{host}}/activ/1653
Authorization: Bearer {{token}}
###
PATCH {{host}}/activ/44?gear=1
Authorization: Bearer {{token}}
###
PATCH  {{host}}/activ/all/8
Authorization: Bearer {{token}}
###
GET    {{host}}/activ/362
Authorization: Bearer {{token}}
###
DELETE {{host}}/activ/1695
Authorization: Bearer {{token}}
###
POST {{host}}/activ
Authorization: Bearer {{token}}

{
  "user_id": 2,
  "what": 1,
  "name": "Fahrt am Morgen",
  "start": "2019-09-24T08:55:12Z",
  "duration": 4868,
  "time": 3331,
  "distance": 18032,
  "climb": 52,
  "descend": 2000,
  "power": 154,
  "gear": 300
}
###
Put {{host}}/activ/1653
Authorization: Bearer {{token}}

{
    "user_id": 2,
    "what": 1,
    "name": "Lenzerheide Worldcup",
    "start": "2019-08-11T10:56:00Z",
    "duration": 21366,
    "time": 9029,
    "distance": 41382,
    "climb": 91,
    "descend": 3571,
    "power": null,
    "gear": 1
 }

###

PATCH {{host}}/activ/rescan
Authorization: Bearer {{token}}

###
GET {{host}}/attach/check/6/10?start=2018-05-30T02:00:00-08:00
Authorization: Bearer {{token}}
###
PATCH {{host}}/attach
Authorization: Bearer {{token}}

 {
    "part_id": 357,
    "gear": 1,
    "hook": 7,
    "attached": "2019-09-30T08:00:00Z"
  }
###
GET {{host}}/attach/332
#?start=2019-09-30T00:00:00Z
#&end=2019-03-30T11:00:00Z
Authorization: Bearer {{token}}
###
GET {{host}}/attach/assembly/11
Authorization: Bearer {{token}}
###
GET  {{host}}/user/test
Authorization: Bearer {{token}}
###
GET  {{host}}/user/
Authorization: Bearer {{token}}
###
POST  {{host}}/user

{
  "lastname": "Müller",
  "firstname": "Hänschen"
}
###
POST {{host}}/activ/descend HTTP/1.1
Authorization: Bearer {{token}}

< /users/christoph/Downloads/Activities_g1.csv
###