services:
  database:
    image: postgres:18-alpine
    volumes:
      - postgres-data:/var/lib/postgresql
    env_file: .env
    network_mode: service:app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    ports:
      - "5173:5173"
    volumes:
      - home:/home/pythia
      - .:/home/pythia/src
      - agentcontainer_workspaces:/workspaces
    command: sleep infinity
    environment:
      - TZ=Europe/Berlin

volumes:
  postgres-data:
  home:
  agentcontainer_workspaces:
    external: true
