services:
  database:
    image: postgres:18-alpine
    volumes:
      - postgres-data:/var/lib/postgresql
    env_file: .env
    
  app:
    image: mcr.microsoft.com/devcontainers/base:trixie
    network_mode: service:database
    init: true
    volumes:
      - ..:/workspaces/tendabike:cached
      - tb_container_home:/home/vscode
      - rust-target:/workspaces/tendabike/target
      - node_modules:/workspaces/tendabike/node_modules
      - agentcontainer_workspaces:/workspaces/agent
    command: sleep infinity
    environment:
      - TZ=${TZ:-Europe/Berlin}

volumes:
  postgres-data:
  rust-target:
  node_modules:
  tb_container_home:
  agentcontainer_workspaces:
    name: agentcontainer_workspaces
