name: Docker Image CI
permissions: 
  contents: read
  actions: read
  packages: write
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ARM64

    steps:
    - uses: actions/checkout@v3
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
    - run: echo ${{ github.event_name }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tendabike
    - name: Tag with PR_# if pull request
      if: github.event_name == 'pull_request'
      run: docker tag tendabike ghcr.io/hcrohland/tendabike:PR_${{ github.event.pull_request.number }}
    - name: Tag as latest if pushed
      if: github.event_name == 'push'
      run: docker tag tendabike ghcr.io/hcrohland/tendabike:latest
    - name: Publish image
      run: docker push -a ghcr.io/hcrohland/tendabike
