name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile.github --tag tendabike:$(date +%s) --tag ghcr.io/hcrohland/tendabike:$(date +%s)
    - name: Push image
      run: docker push ghcr.io/hcrohland/tendabike:$(date +%s)

      
