name: Docker Image CI
permissions: 
  contents: read
  actions: read
  packages: write
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    #runs-on: ubuntu-latest
    runs-on: buildjet-2vcpu-ubuntu-2204-arm

    env: 
      TAG: ${{ github.event_name == 'pull_request' && format('PR_{0}', github.event.pull_request.number) || 'latest'}}
    steps:
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ghcr.io/hcrohland/tendabike:${{ env.TAG }}
        cache-from: type=registry,ref=ghcr.io/hcrohland/tendabike:latest
        cache-to: type=inline