name: Docker Image CI
permissions: 
  contents: read
  actions: read
  packages: write
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    #runs-on: buildjet-2vcpu-ubuntu-2204-arm

    env: 
      TAG: ${{ github.event_name == 'pull_request' && format('PR_{0}', github.event.pull_request.number) || 'latest'}}
    steps:
    - run: echo ${{ env.TAG }}
    - uses: actions/checkout@v3
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tendabike
    - name: Tag as latest if pushed
      if: github.event_name == 'push'
      run: docker tag tendabike ghcr.io/hcrohland/tendabike:${{ env.TAG }}
    - name: Publish image
      run: docker push -a ghcr.io/hcrohland/tendabike
