name: Docker Image CI
permissions: 
  contents: read
  actions: read
  packages: write
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ARM64

    steps:
    - uses: actions/checkout@v3
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
    - run: echo ${{ github.event_name }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/hcrohland/tendabike:${{ github.sha }} 
    - name: Tag as latest if pushed
      if: ${{ github.event.name }} == push
      run: docker tag ghcr.io/hcrohland/tendabike:${{ github.sha }} ghcr.io/hcrohland/tendabike:latest
    - name: Publish image
      run: docker push -a ghcr.io/hcrohland/tendabike
