name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: login to ghcr
      run: docker login -u ${{ github.actor }} -p ${{ github.token }} ghcr.io
#    - name: Build the Docker image
      run: docker build . --file Dockerfile.github --tag ghcr.io/hcrohland/tendabike:${{ github.sha }}
#    - name: Publish image
      run: docker pull ghcr.io/hcrohland/tendabike:${{ github.sha }}
