name: CI
permissions: 
  contents: read
  actions: read
  packages: write
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always

jobs:  
  docker:
    runs-on: ubuntu-latest

    env: 
      TAG: ${{ github.event_name == 'pull_request' && format('PR_{0}, ghcr.io/hcrohland/tendabike:staging', github.event.pull_request.number) || 'latest'}}
    steps:
    - 
      uses: actions/checkout@v4
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - 
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - 
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        file: Dockerfile
        tags: ghcr.io/hcrohland/tendabike:${{ env.TAG }}
        context: .
        cache-from: type=gha
        cache-to: type=gha
      
