name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: hcrohland
          password: ${{ secrets.PAT }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile.hello --tag ghcr.io/hcrohland/tendabike:${{ github.sha }}
    - name: Publish image
      run: docker push ghcr.io/hcrohland/tendabike:${{ github.sha }}
