name: Rust

permissions: 
  contents: read
  actions: read
  packages: write

on:
  #push:
  #  branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        include:
          # intel config
          # - name: linux-amd64
          #   runner: ubuntu-latest
          #   target: x86_64-unknown-linux-gnu
          #   command: cargo
          # arm config
          - name: linux-aarch64
            runner: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            command: cross

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - uses: dtolnay/rust-toolchain@stable
    # Only install cross if we need it
    # Install via cargo-binstall which I found faster
    - name: Install Cross
      if: matrix.command == 'cross'
      shell: bash
      run: |
        curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
        cargo binstall --no-confirm cross

    - name: Build Binary
      run: ${{ matrix.command }} build --locked --release --target ${{ matrix.target }}
    
    - run: cp target/${{ matrix.target }}/release/tendabike .
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Build the Docker image
      run: docker build . --file cross.Dockerfile --tag tendabike
    - name: Tag with PR_# if pull request
      if: github.event_name == 'pull_request'
      run: docker tag tendabike ghcr.io/hcrohland/tendabike:PR_${{ github.event.pull_request.number }}
    - name: Tag as latest if pushed
      if: github.event_name == 'push'
      run: docker tag tendabike ghcr.io/hcrohland/tendabike:latest
    - name: Publish image
      run: docker push -a ghcr.io/hcrohland/tendabike

